version: '3.8'

services:
  fleetpulse-chat:
    build: .
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    environment:
      # GenAI Provider Configuration
      - GENAI_PROVIDER=${GENAI_PROVIDER:-openai}
      
      # API Keys (secure with Docker secrets in production)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://localhost:11434}
      
      # FleetPulse Integration
      - FLEETPULSE_API_URL=${FLEETPULSE_API_URL:-http://fleetpulse-backend:8000}
      - FLEETPULSE_MCP_SERVER=${FLEETPULSE_MCP_SERVER:-./fleetpulse-mcp}
      
      # Application Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_DEBUG=${ENABLE_DEBUG:-false}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
    volumes:
      - ./data:/app/data
    depends_on:
      - fleetpulse-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # FleetPulse Backend (placeholder - would be actual FleetPulse service)
  fleetpulse-backend:
    image: fleetpulse/backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///fleetpulse.db
      - LOG_LEVEL=INFO
    volumes:
      - fleetpulse_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Ollama for local AI
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    profiles:
      - local-ai

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - caching

volumes:
  fleetpulse_data:
  ollama_data:
  redis_data:

networks:
  default:
    name: fleetpulse-network